name: testupload

on:
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - name: Create a test file
        run: echo "test" > test375.txt

      
   
          
  

